spring.application.name=ecomart

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.retry.max-attempts=20
spring.ai.retry.backoff.initial-interval = 10
spring.ai.retry.backoff.max= 300

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# --- CONFIGURACIÓN PARA LA NUBE Y BASE DE DATOS ---

# El servidor de la nube nos dará un puerto, o sino usar el 8080
server.port=${PORT:8080}

# Configuración de PostgreSQL (Railway o Render nos darán estas variables)
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

# Esto permite que Spring cree las tablas automáticamente en mi "PostgreSQL"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect