spring.application.name=ecomart

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.retry.max-attempts=20
spring.ai.retry.backoff.initial-interval=10
spring.ai.retry.backoff.max=300

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# --- CONFIGURACION PARA LA NUBE Y BASE DE DATOS ---

# El servidor de la nube nos dara un puerto o sino usar el 8080
server.port=${PORT:8080}

## Configuracion de PostgreSQL en la nube
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

## Configuracion de H2 para visualizacion de forma local
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# Esto permite que Spring cree las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Configuracion de headers para HTTPS seguro en Railway
server.forward-headers-strategy=framework
springdoc.swagger-ui.supported-submit-methods=get, post, put, delete, patch
springdoc.api-docs.enabled=true